import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-cloud-marketplace-private-offer-reconciliation",
  "engine": "recovery",
  "title": "Cloud Marketplace Private Offer Reconciliation",
  "shortTitle": "Cloud Marketplace Private Offer Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through cloud marketplace private offer reconciliation",
  "industry": "Cloud Marketplace Financial Operations",
  "uiPort": 4628,
  "apiPort": 5628,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Cloud Marketplace Private Offer Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidSettlement",
    "expectedKey": "earnedSettlement",
    "actualLabel": "Paid Marketplace Settlement",
    "expectedLabel": "Calculated Seller Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Cloud Marketplace Private Offer Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("marketplace-offer-library","CMP01","Marketplace offer library","Execute marketplace offer library using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed marketplace offer library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Marketplace offer library Reference","text","CMP01-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("customer-reseller-registry","CMP02","Customer reseller registry","Execute customer reseller registry using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed customer reseller registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Customer reseller registry Reference","text","CMP02-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("product-entitlement-tracking","CMP03","Product entitlement tracking","Execute product entitlement tracking using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed product entitlement tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Product entitlement tracking Reference","text","CMP03-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("usage-metering-ingestion","CMP04","Usage metering ingestion","Execute usage metering ingestion using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed usage metering ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Usage metering ingestion Reference","text","CMP04-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("commitment-drawdown","CMP05","Commitment drawdown","Execute commitment drawdown using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed commitment drawdown decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Commitment drawdown Reference","text","CMP05-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("discount-tier-validation","CMP06","Discount tier validation","Execute discount tier validation using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed discount tier validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Discount tier validation Reference","text","CMP06-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("marketplace-fee-calculation","CMP07","Marketplace fee calculation","Execute marketplace fee calculation using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed marketplace fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Marketplace fee calculation Reference","text","CMP07-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("reseller-margin-calculation","CMP08","Reseller margin calculation","Execute reseller margin calculation using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed reseller margin calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Reseller margin calculation Reference","text","CMP08-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("seller-payout-reconciliation","CMP09","Seller payout reconciliation","Execute seller payout reconciliation using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed seller payout reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Seller payout reconciliation Reference","text","CMP09-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("refund-credit-control","CMP10","Refund credit control","Execute refund credit control using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed refund credit control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Refund credit control Reference","text","CMP10-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("currency-tax-validation","CMP11","Currency tax validation","Execute currency tax validation using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed currency tax validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Currency tax validation Reference","text","CMP11-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("renewal-expiration-monitoring","CMP12","Renewal expiration monitoring","Execute renewal expiration monitoring using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed renewal expiration monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Renewal expiration monitoring Reference","text","CMP12-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("marketplace-dispute-workflow","CMP13","Marketplace dispute workflow","Execute marketplace dispute workflow using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed marketplace dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Marketplace dispute workflow Reference","text","CMP13-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("cash-reconciliation","CMP14","Cash reconciliation","Execute cash reconciliation using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Cash reconciliation Reference","text","CMP14-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]}),
feature("offer-channel-analytics","CMP15","Offer channel analytics","Execute offer channel analytics using marketplace agreements, private offers, customers, resellers, products, entitlements, usage, commitments, discounts, marketplace fees, reseller margins, seller payouts, refunds, taxes, and cash.","Produce a governed offer channel analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Marketplace / Private Offer","text","Marketplace / Private Offer · Standard Case"],["caseReference","Offer channel analytics Reference","text","CMP15-2026-001"],["paidSettlement","Paid Marketplace Settlement","currency",1104500],["earnedSettlement","Calculated Seller Entitlement","currency",1303310],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Marketplace offer library case","Customer reseller registry case","Product entitlement tracking case","Usage metering ingestion case","Commitment drawdown case"]})
]);
